name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do C칩digo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"

      - name: Build com Maven
        run: mvn -B clean install

      - name: Rodar Testes Unit치rios
        run: mvn test

      - name: Gerar Relat칩rio de Cobertura com Jacoco
        run: mvn jacoco:report

      - name: Arquivar Relat칩rios de Cobertura
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/site/jacoco
